In [1]:
x=5
y=7
z=x+y+1

In [2]:
z

13

In [3]:
y=False
type(y)

bool

In [4]:
x="test"
type(x)

str

In [6]:
import pandas as pd
import  numpy as np

df=pd.read_csv('Book1.csv')
print(df)

   roll no              name  UT1  UT2  UT3  UT4
0        1      Perena singh   24   24   20   22
1        2      manish arora   18   17   19   22
2        3       tanish goel   20   22   18   24
3        4           falguni   22   20   24   20
4        5  kanika bhatangar   15   20   18   22
5        6         ramandeep   20   15   22   24


In [7]:
df.max()

roll no              6
name       tanish goel
UT1                 24
UT2                 24
UT3                 24
UT4                 24
dtype: object

In [9]:
print(df.column)

AttributeError: 'DataFrame' object has no attribute 'column'

In [10]:
print(df.columns)

Index(['roll no', 'name', 'UT1', 'UT2', 'UT3', 'UT4'], dtype='object')


In [11]:
print(df.columns())

TypeError: 'Index' object is not callable

In [12]:
print(df.column())

AttributeError: 'DataFrame' object has no attribute 'column'

In [16]:
x='EXAM'
x[::-1]

'MAXE'

In [ ]:
Number = int(input("Enter an integer: "))
Factorial=1
i=Number
while i>1:
    Factorial=Factorial*i
    i=i-1
print("Factorial of",Number,"is",Factorial)

In [ ]:
letter = input("Enter a letter: ")
if letter in ('a','e','i','o','u'):
    print(letter," is a vowel.")
else:
    print(letter,"is a consonant.")

In [ ]:
LIST= []
size = int(input('How many elements you want to enter? '))

print('Enter',str(size),'elements')

for i in range(size):
    data = int(input())
    LIST.append(data)

#reverse the LIST
for i in range(size//2):
    #swapping elements
    LIST[i],LIST[len(LIST)-1-i] = LIST[len(LIST)-1-i], LIST[i]

print('Reverse list:', LIST)

In [9]:
import numpy as np

m=np.random.randint(0,32,(3,4))
n=np.random.randint(0,32,(3,4))
print(m)
print(n)

[[ 1 31  0 15]
 [ 7 17 23 30]
 [ 2 18 12 11]]
[[26 21  5  2]
 [30 30 24 21]
 [12 14 11  3]]


In [12]:
sum(m+n)

array([ 78, 131,  75,  82])

In [22]:
# initializing list
test_list = [3, 5, 7, 9, 11]
  
# printing original list 
print ("The original list is : " + str(test_list))
  
# using sum() + map()
# Cube Summation in List
res = sum(map(lambda i : i * i * i, test_list))
  
# printing result
print ("The sum of cubes of list is : " + str(res))

The original list is : [3, 5, 7, 9, 11]
The sum of cubes of list is : 2555
